"""Limit phone_number to exactly 9 digits

Revision ID: 36dbafdc9534
Revises: add_phone_separation
Create Date: 2026-03-07 15:52:56.238086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36dbafdc9534'
down_revision = 'add_phone_separation'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_admins', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=9),
               existing_nullable=True)

    with op.batch_alter_table('seller_admins', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=9),
               existing_nullable=True)

    with op.batch_alter_table('seller_customers', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=9),
               existing_nullable=True)

    with op.batch_alter_table('seller_deliverers', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=9),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_deliverers', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('seller_customers', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('seller_admins', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('platform_admins', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
