"""Add is_portal_shop column to seller_shops

Revision ID: 6360133e734d
Revises: 82e436d82ea8
Create Date: 2026-05-29 17:15:30.705637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6360133e734d'
down_revision = '82e436d82ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compare_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('import_batch_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_seller_product_sku_unique', ['sku'], unique=True, postgresql_where=sa.text('sku IS NOT NULL'))

    with op.batch_alter_table('seller_shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_portal_shop', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_shops', schema=None) as batch_op:
        batch_op.drop_column('is_portal_shop')

    with op.batch_alter_table('seller_products', schema=None) as batch_op:
        batch_op.drop_index('idx_seller_product_sku_unique', postgresql_where=sa.text('sku IS NOT NULL'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('import_batch_id')
        batch_op.drop_column('sku')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('compare_price')

    # ### end Alembic commands ###
