"""baseline tekanayo clean

Revision ID: 730c7142aef6
Revises: 
Create Date: 2026-03-06 15:59:46.383080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730c7142aef6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_admins_email'), ['email'], unique=True)

    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=120), nullable=True),
    sa.Column('portal_logo_url', sa.String(length=255), nullable=True),
    sa.Column('admin_logo_url', sa.String(length=255), nullable=True),
    sa.Column('deliverer_logo_url', sa.String(length=255), nullable=True),
    sa.Column('seller_login_logo_url', sa.String(length=255), nullable=True),
    sa.Column('deliverer_login_logo_url', sa.String(length=255), nullable=True),
    sa.Column('portal_about_content', sa.Text(), nullable=True),
    sa.Column('portal_legal_content', sa.Text(), nullable=True),
    sa.Column('portal_terms_content', sa.Text(), nullable=True),
    sa.Column('portal_returns_content', sa.Text(), nullable=True),
    sa.Column('portal_privacy_content', sa.Text(), nullable=True),
    sa.Column('admin_about_content', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('facebook_url', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=30), nullable=True),
    sa.Column('whatsapp_group_url', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_url', sa.String(length=255), nullable=True),
    sa.Column('telegram_username', sa.String(length=60), nullable=True),
    sa.Column('telegram_url', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('shipping_cost_out', sa.Float(), nullable=True),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.Column('office_latitude', sa.Float(), nullable=True),
    sa.Column('office_longitude', sa.Float(), nullable=True),
    sa.Column('office_geocoded', sa.Text(), nullable=True),
    sa.Column('exchange_rate_usd_cdf', sa.Float(), nullable=True),
    sa.Column('default_currency', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('seller_space_logo_url', sa.String(length=255), nullable=True),
    sa.Column('deliverer_logo_url', sa.String(length=255), nullable=True),
    sa.Column('owner_email', sa.String(length=120), nullable=False),
    sa.Column('support_email', sa.String(length=120), nullable=True),
    sa.Column('support_phone', sa.String(length=30), nullable=True),
    sa.Column('facebook_url', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=30), nullable=True),
    sa.Column('whatsapp_group_url', sa.String(length=255), nullable=True),
    sa.Column('telegram_username', sa.String(length=60), nullable=True),
    sa.Column('telegram_url', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('about_page_content', sa.Text(), nullable=True),
    sa.Column('legal_page_content', sa.Text(), nullable=True),
    sa.Column('terms_page_content', sa.Text(), nullable=True),
    sa.Column('returns_page_content', sa.Text(), nullable=True),
    sa.Column('privacy_page_content', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('shipping_cost_out', sa.Float(), nullable=True),
    sa.Column('exchange_rate_usd_cdf', sa.Float(), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('invoice_theme', sa.String(length=30), nullable=True),
    sa.Column('category_niche', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_domain')
    )
    with op.batch_alter_table('seller_shops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seller_shops_slug'), ['slug'], unique=True)

    op.create_table('platform_access_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['platform_admins.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['platform_admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=120), nullable=True),
    sa.Column('actor_name', sa.String(length=120), nullable=True),
    sa.Column('actor_phone', sa.String(length=30), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['platform_admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_activity_logs_created_at'), ['created_at'], unique=False)

    op.create_table('platform_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cta_label', sa.String(length=60), nullable=True),
    sa.Column('cta_url', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['platform_admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['seller_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seller_admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seller_admins_email'), ['email'], unique=True)

    op.create_table('seller_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['seller_shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'email', name='uq_seller_customer_shop_email')
    )
    with op.batch_alter_table('seller_customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seller_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_customers_shop_id'), ['shop_id'], unique=False)

    op.create_table('seller_deliverers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['seller_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seller_deliverers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seller_deliverers_email'), ['email'], unique=True)

    op.create_table('seller_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_promoted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['seller_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('deliverer_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['seller_customers.id'], ),
    sa.ForeignKeyConstraint(['deliverer_id'], ['seller_deliverers.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['seller_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller_orders')
    op.drop_table('seller_products')
    with op.batch_alter_table('seller_deliverers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seller_deliverers_email'))

    op.drop_table('seller_deliverers')
    with op.batch_alter_table('seller_customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seller_customers_shop_id'))
        batch_op.drop_index(batch_op.f('ix_seller_customers_email'))

    op.drop_table('seller_customers')
    with op.batch_alter_table('seller_admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seller_admins_email'))

    op.drop_table('seller_admins')
    op.drop_table('platform_announcements')
    with op.batch_alter_table('platform_activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_activity_logs_created_at'))

    op.drop_table('platform_activity_logs')
    op.drop_table('platform_access_requests')
    with op.batch_alter_table('seller_shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seller_shops_slug'))

    op.drop_table('seller_shops')
    op.drop_table('platform_settings')
    with op.batch_alter_table('platform_admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_admins_email'))

    op.drop_table('platform_admins')
    # ### end Alembic commands ###
