"""Add AdminNotification model and is_viewed field to SellerPaymentTask for notification badge system

Revision ID: 7b4411ab6a8c
Revises: 5f0b424c3b2a
Create Date: 2026-03-13 08:34:23.078099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4411ab6a8c'
down_revision = '5f0b424c3b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_payment_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_viewed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('viewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('viewed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_payment_task_viewed', 'platform_admins', ['viewed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_payment_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_task_viewed', type_='foreignkey')
        batch_op.drop_column('viewed_by')
        batch_op.drop_column('viewed_at')
        batch_op.drop_column('is_viewed')

    # ### end Alembic commands ###
