"""add_platform_deliverers_table

Revision ID: 8382dd9f336b
Revises: 86a5b7776c54
Create Date: 2026-05-01 19:25:20.075512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8382dd9f336b'
down_revision = '86a5b7776c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_deliverers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('phone_number', sa.String(length=9), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_deliverers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_deliverers_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_deliverers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_deliverers_email'))

    op.drop_table('platform_deliverers')
    # ### end Alembic commands ###
