"""Add document upload fields to SellerShop for seller verification

Revision ID: 9b30d0ac10ff
Revises: 7b4411ab6a8c
Create Date: 2026-03-13 11:20:32.893461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b30d0ac10ff'
down_revision = '7b4411ab6a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_document_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('address_document_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verification_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_seller_verified_by', 'platform_admins', ['verified_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_shops', schema=None) as batch_op:
        batch_op.drop_constraint('fk_seller_verified_by', type_='foreignkey')
        batch_op.drop_column('verification_notes')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verified_by')
        batch_op.drop_column('verification_status')
        batch_op.drop_column('address_document_path')
        batch_op.drop_column('id_document_path')

    # ### end Alembic commands ###
